version: "3.8"

services:
    db:
        image: mysql
        container_name: team_datum
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: "password123"
        volumes:
            - "./db:/var/lib/mysql"
        ports: 
            - "33066:3306"
    adminer:
        image: adminer
        container_name: team_datum_container
        restart: always
        ports:
            - 8080:8080
    grafana:
        image: grafana/grafana
        container_name: grafana_container
        ports:
            - 8000:3000
        