service: fbl-serverless-demo
frameworkVersion: "2"

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  profile: learner
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ec2:DescribeNetworkInterfaces"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ec2:DeleteNetworkInterface"
      Resource:
        - "*"
  vpc:
    securityGroupIds:
      - sg-022819bef83110bea
    subnetIds:
      - subnet-0f37ee489a186d9a5
      - subnet-0240f67155c6bd934
      - subnet-0ca1a4a748dc923ee

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: ${env:BUCKET}
          event: s3:ObjectCreated:*
          rules: 
            - prefix: incoming/
            - suffix: .csv

